name: "publish"

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
            artifact_name: "imshow-macos-aarch64.zip"
            binary: "src-tauri/target/aarch64-apple-darwin/release/imshow" 
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
            artifact_name: "imshow-macos-x86_64.zip"
            binary: "src-tauri/target/x86_64-apple-darwin/release/imshow"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
            artifact_name: "imshow-linux.zip"
            binary: "src-tauri/target/release/imshow"
          - platform: "windows-latest"
            args: ""
            artifact_name: "imshow-windows.zip"
            binary: "src-tauri/target/release/imshow.exe"

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        id: tauri-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: imshow-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: "imshow v__VERSION__"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}